name: Release

on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run prepublish
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ridedott/release-me-action@master
      # - name: Modify package.json contents for github registry
      #   run: ./.github/scripts/release.sh
      #   shell: bash
      # - run: npm publish --@abigger87:registry=https://npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
